version: '3.5'
services:
      nginx:
            image: nginx:mainline
            container_name: jusan-nginx-final
            ports:
                  - 8787:80
            volumes:
                  - ./jusan-docker-mount.conf:/etc/nginx/conf.d/default.conf
                  - ./jusan-docker-mount:/var/www/example
                  - ./jusan-fastapi-final.conf:/etc/nginx/conf.d/jusan-fastapi-final.conf
            restart: unless-stopped
            depends_on:
                  - api
      api:
            image: jusan-fastapi-final:dockerized
            container_name: jusan-compose-final
            ports:
                  - 80:80
